##########################################################
# Multivariate DE analysis tool                          #
#--------------------------------------------------------#
# File Name: Docker                                      #
# Programmer: Sarah Vang (sarah.vang@q2labsolutions.com  #
# Last edit: 7/16/2020                                   #
# Server: vsd_docker01                                   #
#--------------------------------------------------------#
#Description:                                            #
# Dockerizing the DESeq2 and limma tool to run           #
# Multivariate DE analysis on the command line. For this #
# docker, we install R packages on the ADC. This         #
# Dockerfile starts from a R-4.0.0 docker image, adds    #
# additional R packages, and establishes the main        #
# directory (./) as the main place for a user to run the #
# program.                                               #
##########################################################
 
FROM r-base:4.0.0
#-------------------------------------------------------------
# INSTALL R and PACKAGES
#-------------------------------------------------------------
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    lbzip2 \
    libfftw3-dev \
    libgdal-dev \
    libgeos-dev \
    libgsl0-dev \
    libgl1-mesa-dev \               #Required system to install 'rgl'
    libglu1-mesa-dev \
    libhdf4-alt-dev \
    libhdf5-dev \
    libjq-dev \
    libpq-dev \
    libproj-dev \
    libprotobuf-dev \
    libnetcdf-dev \
    libsqlite3-dev \
    libssl-dev \
    libudunits2-dev \
    netcdf-bin \
    postgis \
    protobuf-compiler \
    sqlite3 \
    tk-dev \
    unixodbc-dev
 
RUN install2.r --error \
    RColorBrewer
# Needed for proper compile
 
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org';options(repos = r);" > ~/.Rprofile
RUN Rscript -e "sessionInfo()"
RUN Rscript -e "if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager', repos='http://cran.us.r-project.org')"
RUN Rscript -e "BiocManager::install('DESeq2')"
RUN Rscript -e "BiocManager::install('limma')"
RUN Rscript -e "BiocManager::install('edgeR')"
RUN Rscript -e "BiocManager::install('EnhancedVolcano')"
RUN Rscript -e "install.packages('tidyverse', repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('pca3d', dependencies=TRUE, repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('pheatmap', repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('getopt', repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('RColorBrewer', repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('viridis', repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('factoextra', repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('NbClust', repos='http://cran.us.r-project.org')"
RUN Rscript -e "install.packages('ggrepel', repos='http://cran.us.r-project.org')"
RUN Rscript -e "library(DESeq2);library(pca3d);library(NbClust);library(pca3d);library(RColorBrewer);library(EnhancedVolcano)"
